export const MESSAGING_UI_TEST = {
  PATH: '/?messaging=1',
  CONTROL_API: '/api/notification-fixture',
  LABEL: 'Сообщение',
  SEND: 'Отправить сообщение',
  OPEN_A: 'Открыть историю А',
  OPEN_B: 'Открыть историю Б',
  DRAFT: 'Новый черновик',
  REPLY_TEXT: 'Ответ тестового собеседника',
  CONTROL_SIZE: 43,
  SINGLE_LINE: 'Привет',
  OVERSIZED_TEXT: '🙂'.repeat(4097),
  ENTER: 'Enter',
  TEXT: '  Тестовое сообщение\n🙂  ',
  ACCEPTED: 'Принято API',
  READ: 'Прочитано',
  DELIVERED: 'Доставлено',
  FAILED: 'Ошибка отправки',
  VIEWPORT_WIDTHS: [1280, 360, 320],
  FAILURE: 'Получатель недоступен',
  LIVE_TEXT: 'Новое входящее сообщение',
  LIMIT: 'Рабочий чат уже открыт в другой вкладке.',
} as const
