export const UNREAD_TEST = {
  KEY: 'chat-unread',
  OTHER_CHAT: '10000002',
  UNKNOWN_CHAT: '10000003',
  SECOND_MESSAGE: 'unread-message-2',
  STALE_SCOPE: 'unread-foreign-scope',
  STALE_OWNER: 'unread-foreign-owner',
  PATH: '/?unread=1',
  COUNT_LABEL: 'Новых сообщений:',
  BACK: 'Чаты',
  CLOSE: 'Закрыть чат',
  VISIBLE: 'visible',
  HIDDEN: 'hidden',
  VISIBILITY_EVENT: 'visibilitychange',
  VISIBILITY_PROPERTY: 'visibilityState',
  MAX_LABEL: '99+',
  CHAT_A: 'История А',
  CHAT_B: 'История Б',
  UNKNOWN_LABEL: 'Тестовый собеседник',
  ACCOUNT: '@demo_account',
  LOGOUT: 'Выйти',
  LONG_LABEL: 'ДлинноеИмяСобеседника'.repeat(8),
  COUNTS: 'unread-counts',
  FOREIGN_DELIVERY: 'foreign-delivery',
  TEXT: 'Входящее для счётчика',
  ID_PREFIX: 'unread-incoming-',
  WIDTHS: [1280, 390, 320],
  HEIGHT: 800,
  MOBILE_BREAKPOINT: 680,
  PREVIEW_TIMEOUT_MS: 25_000,
  PREVIEW_TEST_TIMEOUT_MS: 35_000,
  OVER_LIMIT: 100,
  ROW_MAX_HEIGHT: 80,
  HEADER_NAME_MAX_HEIGHT: 24,
  SCREENSHOT_PREFIX: 'unread-preview',
} as const
